base = 0
first = 35
seccond = 40 
 
configuracion_lineas = { 
     
    0:   {'tamano_fuente': 7,    'alineacion': 'right',   'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    1:   {'tamano_fuente': 7,    'alineacion': 'justify', 'justificado': True,  'indentacion': base   , 'espaciado_despues': 2},
    2:   {'tamano_fuente': 10,   'alineacion': 'center',  'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    3:   {'tamano_fuente': 8,   'alineacion': 'left',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    4:   {'tamano_fuente': 7,    'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    5:   {'tamano_fuente': 7,    'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    6:   {'tamano_fuente': 7,    'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    7:   {'tamano_fuente': 7,    'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    8:   {'tamano_fuente': 7,    'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    9:   {'tamano_fuente': 8,   'alineacion': 'left',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    10:  {'tamano_fuente': 7,   'alineacion': 'left',    'justificado': False, 'indentacion': first  , 'espaciado_despues': 2},
    11:  {'tamano_fuente': 7,   'alineacion': 'left',    'justificado': False, 'indentacion': first  , 'espaciado_despues': 2},
    12:  {'tamano_fuente': 7,   'alineacion': 'left',    'justificado': False, 'indentacion': first  , 'espaciado_despues': 2},
    13:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    14:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    15:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    16:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    17:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    18:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    19:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    20:  {'tamano_fuente': 8,  'alineacion': 'left',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    21:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    22:  {'tamano_fuente': 10,  'alineacion': 'center',  'justificado': False, 'indentacion': first  , 'espaciado_despues': 2},
    23:  {'tamano_fuente': 7,   'alineacion': 'left',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    24:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    25:  {'tamano_fuente': 7,   'alineacion': 'left',    'justificado': False, 'indentacion': first  , 'espaciado_despues': 2},
    26:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    27:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    28:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    29:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    30:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    31:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    32:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    33:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    34:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    35:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    36:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    37:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    38:  {'tamano_fuente': 7,   'alineacion': 'Left', 'justificado': False,  'indentacion': base   , 'espaciado_despues': 2},
    39:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    40:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    41:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    42:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    43:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    44:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    45:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    46:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    47:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    48:  {'tamano_fuente': 7,   'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    49:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    50:  {'tamano_fuente': 7,   'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    51:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    52:  {'tamano_fuente': 7,   'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    53:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    54:  {'tamano_fuente': 7,   'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    55:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    56:  {'tamano_fuente': 7,   'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    57:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    58:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    59:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    60:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    61:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    62:  {'tamano_fuente': 7,   'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    63:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    64:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    66:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    67:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    68:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    69:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 20, 'espaciado_despues': 2},
    70:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    71:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    72:  {'tamano_fuente': 6,   'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    73:  {'tamano_fuente': 6,  'alineacion': 'center',  'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    74:  {'tamano_fuente': 6,  'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    75:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    76:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    77:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': base, 'espaciado_despues': 2},
    78:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    79:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    80:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    81:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    82:  {'tamano_fuente': 10,   'alineacion': 'center', 'justificado': False,  'indentacion': seccond, 'espaciado_despues': 2},
    83:  {'tamano_fuente': 8,  'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    84:  {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': first   , 'espaciado_despues': 2},
    85:  {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': first   , 'espaciado_despues': 2},
    86:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first, 'espaciado_despues': 2},
    87:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first, 'espaciado_despues': 2},
    88:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first, 'espaciado_despues': 2},
    89:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first, 'espaciado_despues': 2},
    90:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first, 'espaciado_despues': 2},
    91:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    92:  {'tamano_fuente': 8,   'alineacion': 'left', 'justificado': False,  'indentacion': base, 'espaciado_despues': 2},
    93:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': base, 'espaciado_despues': 2},
    94:  {'tamano_fuente': 7,   'alineacion': 'left', 'justificado': False,  'indentacion': base, 'espaciado_despues': 2},
    95:  {'tamano_fuente': 7,  'alineacion': 'left',    'justificado': True, 'indentacion': first   , 'espaciado_despues': 2},
    96:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    97:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    98:  {'tamano_fuente': 7,  'alineacion': 'left',  'justificado': False, 'indentacion': first   , 'espaciado_despues': 2},
    99:  {'tamano_fuente': 7,  'alineacion': 'left',    'justificado': False, 'indentacion': first   , 'espaciado_despues': 2},
    100:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    101: {'tamano_fuente': 7,  'alineacion': 'bold',   'justificado': False, 'indentacion': first   , 'espaciado_despues': 2},
    102: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    103: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    104: {'tamano_fuente': 8,  'alineacion': 'left', 'justificado': False,  'indentacion': base, 'espaciado_despues': 2},
    105: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    106: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    107: {'tamano_fuente': 10,  'alineacion': 'center', 'justificado': False,  'indentacion': seccond, 'espaciado_despues': 2},
    108: {'tamano_fuente': 8,  'alineacion': 'left', 'justificado': False,  'indentacion': base, 'espaciado_despues': 2},
    109: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': base, 'espaciado_despues': 2},
    110: {'tamano_fuente': 8,  'alineacion': 'left', 'justificado': False,  'indentacion': base, 'espaciado_despues': 2},
    111: {'tamano_fuente': 7, 'alineacion': 'left',    'justificado': True, 'indentacion': base   , 'espaciado_despues': 2},
    112: {'tamano_fuente': 7,  'alineacion': 'left', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    113: {'tamano_fuente': 7,  'alineacion': 'left', 'justificado': True,  'indentacion': first, 'espaciado_despues': 2},
    114: {'tamano_fuente': 7,  'alineacion': 'left', 'justificado': True,  'indentacion': first, 'espaciado_despues': 2},
    115: {'tamano_fuente': 7, 'alineacion': 'left',    'justificado': True, 'indentacion': first   , 'espaciado_despues': 2},
    116: {'tamano_fuente': 7,  'alineacion': 'left', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    117: {'tamano_fuente': 7, 'alineacion': 'left',    'justificado': True, 'indentacion': first   , 'espaciado_despues': 2},
    118: {'tamano_fuente': 7,  'alineacion': 'left', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    119: {'tamano_fuente': 7, 'alineacion': 'left',    'justificado': True, 'indentacion': first   , 'espaciado_despues': 2},
    120: {'tamano_fuente': 8,  'alineacion': 'left', 'justificado': False,  'indentacion': base  , 'espaciado_despues': 2},
    121: {'tamano_fuente': 7, 'alineacion': 'left',    'justificado': True, 'indentacion': base   , 'espaciado_despues': 2},
    122: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    123: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': seccond, 'espaciado_despues': 2},
    124: {'tamano_fuente': 8,  'alineacion': 'left', 'justificado': False,  'indentacion': base, 'espaciado_despues': 2},
    125: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': base, 'espaciado_despues': 2},
    126: {'tamano_fuente': 8, 'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    127: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': base  , 'espaciado_despues': 2},
    128: {'tamano_fuente': 8, 'alineacion': 'bold',    'justificado': False, 'indentacion': base   , 'espaciado_despues': 2},
    129: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': base  , 'espaciado_despues': 2},
    130: {'tamano_fuente': 8,  'alineacion': 'left', 'justificado': False,  'indentacion': base  , 'espaciado_despues': 2},
    131: {'tamano_fuente': 7,  'alineacion': 'left', 'justificado': True,  'indentacion': base  , 'espaciado_despues': 2},
    132: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    133: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    134: {'tamano_fuente': 7,  'alineacion': 'justify', 'justificado': True,  'indentacion': first  , 'espaciado_despues': 2},
    135: {'tamano_fuente': 8,  'alineacion': 'left', 'justificado': False,  'indentacion': base  , 'espaciado_despues': 2},
    136: {'tamano_fuente': 7,  'alineacion': 'left', 'justificado': True,  'indentacion': base  , 'espaciado_despues': 2},
    137: {'tamano_fuente': 8,  'alineacion': 'left', 'justificado': False,  'indentacion': base  , 'espaciado_despues': 2},
    138: {'tamano_fuente': 7,  'alineacion': 'left', 'justificado': True,  'indentacion': base  , 'espaciado_despues': 2},
    139: {'tamano_fuente': 7,  'alineacion': 'left', 'justificado': True,  'indentacion': base  , 'espaciado_despues': 2},
    147:  {'tamano_fuente': 8,   'alineacion': 'left', 'justificado': False,  'indentacion': 30, 'espaciado_despues': 2},
    148:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    149:  {'tamano_fuente': 7,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    153:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    154:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    155:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    156:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    157:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 20, 'espaciado_despues': 2},
    158:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    159:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},
    160:  {'tamano_fuente': 6,   'alineacion': 'justify', 'justificado': True,  'indentacion': 30, 'espaciado_despues': 2},

}
